id: I9E21A861
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T19:53:23+00:00'
last_modified: '2022-06-08T02:45:11.820664+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W3CN2456
  title: འབྲུག་ལུགས་འདོན་ཆོག་སྣ་ཚོགས་ཕྱོགས་བསྡུས།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '5729':
      image_group_id: I3CN2458
      title: ''
      total_pages: 403
      order: 1
      base_file: 5729.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
